system-ghc: true
snapshot: ghc-9.8.4
nix:
  enable: true
  # true by default. Tells Nix whether to run in a pure shell or not.
  pure: true

  # Empty by default. The list of packages you want to be
  # available in the nix-shell at build time (with `stack
  # build`) and run time (with `stack exec`).
  packages: []

  shell-file: shell.nix

  # A list of strings, empty by default. Additional options that
  # will be passed verbatim to the `nix-shell` command.
  nix-shell-options: []

  # A list of strings, empty by default, such as
  # `[nixpkgs=/my/local/nixpkgs/clone]` that will be used to override
  # NIX_PATH.
  path: []
  notify-if-nix-on-path: false

extra-deps:
  - markdown-unlit-0.6.0
  - base-compat-0.14.1
# extra-deps:
#   - base-compat-0.14.1@sha256:d01078dff437dd547942a6f12389f1cc874328c1d61c0b795b9a6b822f133c96,7592
#    - markdown-unlit-0.6.0@sha256:8a26dabe29b98f7ca3cf76afcf52b082431511c03563dc1128be23c91d357994,1763
